env:
    es6: true
    node: true

globals:
    assert: true
    browser: true
    expect: true

parserOptions:
    ecmaVersion: 6
    sourceType: module

root: true

plugins:
    - wdio

extends:
    - plugin:wdio/recommended

rules:
    comma-dangle:
        - 'error'
        - arrays: 'always-multiline'
          objects: 'always-multiline'
          exports: 'never'
          functions: 'ignore'
    indent:
        - 'warn'
        - 4
        - SwitchCase: 1
    max-len:
        - 'error'
        - 160
        - ignorePattern: '\s*\/\^(.*)\$\/,$'
    new-cap:
        - 'error'
        - newIsCap: true
          capIsNewExceptions:
              - 'Given'
              - 'When'
              - 'Then'
    require-jsdoc:
        - 'error'
        - require:
              FunctionDeclaration: false
              MethodDefinition: false
              ClassDeclaration: false
    strict: 'off'
    valid-jsdoc:
        - 'warn'
        - requireReturn: false
          matchDescription: '.+'
